@startuml
class HighwayScene extends GameObject {
    #onEnable(): void
    +loadGame(songId: string): void
}
Mode --> "*" Note
NotesManagerLogicBehavior --> "*" FretLogicBehavior
NotesManagerLogicBehavior --> "*" NoteGameObject
FretHandleGameObject --> "*" FretLogicBehavior
Chart --> "*" Mode
MidiParser --> "*" Note
ChartParser --> "*" Mode
ChartParser --> "*" Note
HighwayScene --> "1" SongSelectionGameObject
@enduml